# Generated by Django 6.0.7 on 2026-09-18 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_likes_post_pinned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pinned', '-created_at']},
        ),
    ]
